
home:
  host: 0.0.0.0:5000
  handle: juicy-cove-4582
  email: manuchap@gmail.com
  api_key: c19fc1a4bf16d914fbf7fcad33119a470c51e09b

back:
  host: manuchap.herokuapp.com
  handle: thoughtless-drylands-9499
  email: admin@studiowan.fr
  api_key: bb3be4f0209440288523f2b4ed6894fe2dd868d3
