title:
  en: 'TGV: Train with Great Velocity'
  fr: 'TGV: Train à Grande Vitesse'
home:
  en: Home
  fr: Accueil
hello:
  en: Hello
  fr: Bonjour
guest:
  en: guest
  fr: invité
whos:
  en: by
  fr: par
